FROM node:14

WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install backend dependencies
RUN npm install

# Copy the rest of your backend application files
COPY . .

EXPOSE 5000

CMD ["npm", "start"]
